version: "3"
services:
  helloworld:
    image: adamgolab/hello-world
    env_file: 
      - "./.env.helloworld"
    ports:
      - "${HOST:-0.0.0.0}:${PORT:-3000}:8000"
    volumes: ["${STATE_DIR:-./state}/inhost:/incontainer"]
